### PR TITLE
migration to nav.tum.de

### PR DESCRIPTION
**Pull request by CommanderStorm**
This PR fully migrates us to nav.tum.de

Requires #211 to be merged first for building the `data`/`server`/`meilisearch` dockerfile

### CODE REVIEW

**Comment by CommanderStorm** [comment]
This PR is blocked by a needed change to our DNS situation

**Comment by kordianbruck** [comment]
Let me know if I can help somehow, but I guess you mean the CNAME that we are requesting from TUM, right?

**Comment by CommanderStorm** [comment]
> Let me know if I can help somehow, but I guess you mean the CNAME that we are requesting from TUM, right?

I would have already talked to you, If I needed something. 😉 

Anything in this PR is:
 - `nav.tum.sexy` now redirects via 302 to `nav.tum.de`
 - `nav.tum.app` now redirects via 302 to `nav.tum.de`
 - `nav.tum.de` is already supported by us (we could serve from it, if a ´CNAME´ existed)

**Comment by CommanderStorm** [comment]
@octycs We have done it. DNS is set. There are a few minor things, I have to clean up, but we now serve from 
https://nav.tum.de

**Pull request merged**
