### PR TITLE
[data-scraper-1] Data-Update

### PR DESCRIPTION
**Pull request by CommanderStorm**
This is a temporary fix for our data being out of date
The prevous change #427 broke because of [multiple issues we overlooked](https://github.com/TUM-Dev/NavigaTUM/actions/runs/4341914493/jobs/7582104373)

## Proposed Changes (include Screenshots if possible)

- ran the scraper
- Fixed any upcoming issues (This is TODO at the moment)

## How to test this PR

1. Look if the changes are good or if anything needs to be patched

## How has this been tested?

- Looked if the changes are good or if anything needs to be patched

## Checklist:

- [x] I have updated the documentation / No need to update the documentation
- [x] I have run the linter

### CODE REVIEW

**Comment by CommanderStorm** [comment]
@octycs there were some buildings removed in the MyTUM Roomfinder (this stopped the build)

Seeing that the [log for this job](https://github.com/TUM-Dev/NavigaTUM/actions/runs/4346757353/jobs/7593226733) is still slightly different from the [previous log](https://github.com/TUM-Dev/NavigaTUM/actions/runs/4343773140/jobs/7586249270), do you think we can merge this and do it in another PR, or fix it in this PR?

**Comment by octycs** [comment]
It seems to me like the changes in the log are mostly fine, because buildings are just removed (the ones at the Olympiapark and "5110 Trafostation PH (Abriss ca. Okt. 2021?)"). They have apparently now finally fixed `4234.EG.533^` -> `4234.EG.533`, so we can get rid of the [patch](https://github.com/TUM-Dev/NavigaTUM/blob/3abc7cebd88cd1886117e2a770493fa278356bf1/data/sources/15_patches-rooms_tumonline.yaml#L22)

Apart from that I don't see anything that we need to update, or is there more?

**Comment by CommanderStorm** [comment]
The main reason why I am slightly concerned, is that the list of rooms in the Roomfinder that we cannot match has grown by this amount:
```
WARNING: Could not find roomfinder room in TUMonline data: -1110A@0501 # https://nav.tum.de/room/0501.U1.110A
WARNING: Could not find roomfinder room in TUMonline data: -1190A@0501 #https://nav.tum.de/room/0501.U1.190A
WARNING: Could not find roomfinder room in TUMonline data: -1190B@0501
WARNING: Could not find roomfinder room in TUMonline data: -1199A@0501
WARNING: Could not find roomfinder room in TUMonline data: 0114A@0501
WARNING: Could not find roomfinder room in TUMonline data: 0116@0501
WARNING: Could not find roomfinder room in TUMonline data: 0139@0501
WARNING: Could not find roomfinder room in TUMonline data: 0139A@0501
WARNING: Could not find roomfinder room in TUMonline data: 1130B@0501
WARNING: Could not find roomfinder room in TUMonline data: 1139@0501
WARNING: Could not find roomfinder room in TUMonline data: 1139A@0501
WARNING: Could not find roomfinder room in TUMonline data: 1143A/G@0501
WARNING: Could not find roomfinder room in TUMonline data: 1152A@0501
WARNING: Could not find roomfinder room in TUMonline data: 1172A@0501
WARNING: Could not find roomfinder room in TUMonline data: 1172B@0501
WARNING: Could not find roomfinder room in TUMonline data: 2119@0501
WARNING: Could not find roomfinder room in TUMonline data: 2139@0501
```
```
WARNING: Could not find roomfinder room in TUMonline data: 2140A@0501 # https://nav.tum.de/room/0501.02.140A
WARNING: Could not find roomfinder room in TUMonline data: 2150@0501 # https://nav.tum.de/room/0501.02.150
```
```
WARNING: Could not find roomfinder room in TUMonline data: 3139@0501
WARNING: Could not find roomfinder room in TUMonline data: 3139A@0501
WARNING: Could not find roomfinder room in TUMonline data: 3150@0501
WARNING: Could not find roomfinder room in TUMonline data: 3150A@0501
```
```
WARNING: Could not find roomfinder room in TUMonline data: 4149@0501
WARNING: Could not find roomfinder room in TUMonline data: 4149A@0501
WARNING: Could not find roomfinder room in TUMonline data: 4150@0501
WARNING: Could not find roomfinder room in TUMonline data: 4150A@0501
WARNING: Could not find roomfinder room in TUMonline data: 5158Z@0501
WARNING: Could not find roomfinder room in TUMonline data: G 5158A@0501
```

Is this intended/should this be concerning?

**Comment by octycs** [comment]
Unfortunately I don't know whether they are intended or not, but I know that (since all changes concern 0501) this building was also where we recently got a request from ZA4 concerning one of the rooms above. The room does indeed no longer exist in TUMonline (and also no room of equal surface area, so it wasn't a simple rename). According to their response, there have at least been some construction works in this building, which might explain the changes.

So overall, I don't know what the real situation is like at the moment, but it seems rather intentional than unintentional, because it's more specific edits. On the other hand it is not clear for me from ZA4's response, if the issue is resolved. I would nonetheless merge.

**Pull request merged**
