### PR TITLE
[NAT-2] Extra/Explanatory information field

### PR DESCRIPTION
**Pull request by CommanderStorm**
Related to #34 

## Proposed Changes (include Screenshots if possible)

- Added an extra info filed to the information card
- This card looks like this: 
  image

## How to test this PR

1. Launch the webclient
2. open the vue console
3. navigate to the details view
4. under `view_data.props.computed[0]`: add `extra: {}`
5. add `view_data.props.computed[0].extra.header: "This is the Header of the info field"`
6. add `view_data.props.computed[0].extra.header: "This is the body of the info field"`

## How has this been tested?

- visual checking if this looks good

## Checklist:

- [x] I have updated the documentation / No need to update the documentation
- [x] I have run the linter

### CODE REVIEW

**Comment by octycs** [comment]
image

I think on mobile it's better to open a modal instead, because hover doesn't work on touch. And also sometimes the popover is clipped to the side.

**Comment by CommanderStorm** [comment]
I dont like that this is another modal in the code from a code-duplication standpoint, but accept that until we get #200 off the ground this is the best we can do..

**Comment by CommanderStorm** [comment]
Works as expected. From my perspective, we could merge this.

**Comment by octycs** [comment]
> I dont like that this is another modal in the code from a code-duplication standpoint, but accept that until we get #200 off the ground this is the best we can do..

I also don't like the code-duplication, but from an UX perspective I think a modal is better there

**Comment by octycs** [comment]
https://github.com/TUM-Dev/NavigaTUM/pull/355/commits/15b5d2c797ee13f2070298d9c032e88eed97d8d4 adds some shadow to the popover and makes its header bold:

image

https://github.com/TUM-Dev/NavigaTUM/pull/355/commits/35d34ffd99078e6ed6933f3617a11dc9de2bd5ff fixes a bug where the modal is briefly visible on pageload.

If you're okay with these changes I'd also ready to merge.

**Review by octycs — APPROVED** [review]

**Pull request merged**
