### PR TITLE
Image-showcase

### LINKED ISSUE #89: [Feature] image carousel
**Is your feature request related to a problem? Please describe.**
We currently supply multiple images for some buildings. In the frontend we however show only one size (`header`)

**Describe the solution you'd like**
It would be cool to have a image carousel pop up, once a user presses on the image with all of our images.
The image should be marked up via [googles image licence structured data](https://developers.google.com/search/docs/advanced/structured-data/image-license-metadata).
It would also be preferable to include the images via a sourceset, since we include multiple sizes for each image (`sm`,`md`,`lg`)

**Describe alternatives you've considered**
Keep it as is and only show one image. Not ideal, but it works

### PR DESCRIPTION
**Pull request by CommanderStorm**
this PR adds an image showcase, for all the beautiful images we have.

UI samples:
Screenshot_20220509_233042
Screenshot_20220509_233008

resolves #89

### CODE REVIEW

**Comment by octycs** [comment]
I'm having some issues with the CSS. Below the images there is the license / source text, but cropped:
image

However the visible source section below that doesn't update when I change the image.

**Comment by CommanderStorm** [comment]
> I'm having some issues with the CSS. Below the images there is the license / source text, but cropped: image
> 
> However the visible source section below that doesn't update when I change the image.

Good catch. My browser did not display that.

The fix for the sidebar issue however is less pretty:
I rely on the undocumented (!) `modal-fullheight`
from https://github.com/picturepan2/spectre/blob/master/src/_modals.scss

**Comment by CommanderStorm** [comment]
I think all the issues should be fixed now.
Could you recheck if it works on your end?

The CSS-issue of the images loading in/out weird (if aspact ratio is not a match) is nothing that I can fix as far as I can tell, but this could also be me doing frontend stuff...

**Comment by octycs** [comment]
That text issue is solved now. But I'm still only seeing the source of the first image when sliding through them.

That CSS issue is a bit annoying, yeah. But I also couldn't find a quick fix. It's hardcoded into spectre. The only we could do easily is turn the animation there off.

**Comment by octycs** [comment]
> But I'm still only seeing the source of the first image when sliding through them.

Ah okay, that issue is only there when I use the buttons at the bottom. When I'm using the right/left arrows it works

**Comment by CommanderStorm** [comment]
Where (browser, url) is this the case?
Every big building with different sources (not all images have distinct sources) works on my machine.

**Comment by octycs** [comment]
E.g. `/building/mw` with Firefox 100.0 and Chromium (Version 101.0.4951.54 (Official Build) Manjaro Linux (64-bit))

**Comment by octycs** [comment]
I'll try to look into it tomorrow

**Comment by CommanderStorm** [comment]
Sorry Per André for the accidental ping...

**Comment by octycs** [comment]
> https://github.com/TUM-Dev/navigatum/pull/108/commits/dd0823e68fae5d586214b78b5e9c4df105a77275

Yup that solves it.

**Review by octycs — APPROVED** [review]
I think it's fine like this, though we might turn animations off or find a fix for that sometimes glitchy look.

**Comment by CommanderStorm** [comment]
> I think it's fine like this, though we might turn animations off or find a fix for that sometimes glitchy look.

Sadly If we want to fix it we will have to do that ourselves, since spectre.css is not anylonger maintained.

This can however be a main-commit-bugfix or another PR. I am merging this and creating an issue

**Pull request merged**
